const menuData = {
  entrantes: [
    {
      image: "https://media.istockphoto.com/id/1400487647/photo/slices-of-jamon-serrano-ham-or-prosciutto-crudo-parma-on-wooden-board-with-rosemary-wooden.jpg?s=2048x2048&w=is&k=20&c=PCi0o_AIV7HYy7XMWqzTBHQyPOQWEp5c--y0B5xCtew=",
      title: "Croquetas de Jamón",
      description: "Deliciosas croquetas cremosas con trozos de jamón serrano de primera calidad.",
      ingredients: "Leche, harina, mantequilla, jamón serrano, pan rallado, huevo.",
      allergens: ["Gluten", "Huevo", "Lácteos"],
      price: "8.50 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2015/11/16/14/50/calamari-1045797_1280.jpg",
      title: "Calamares a la Romana",
      description: "Calamares tiernos rebozados en una masa ligera y crujiente, acompañados de alioli casero.",
      ingredients: "Calamares, harina, huevo, limón, sal, aceite de oliva.",
      allergens: ["Gluten", "Huevo", "Moluscos"],
      price: "10.95 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2015/01/20/13/30/france-605450_1280.jpg",
      title: "Tabla de Quesos",
      description: "Selección de quesos nacionales e internacionales servidos con nueces, mermeladas artesanales y pan de centeno.",
      ingredients: "Queso manchego, queso azul, brie, cabra, nueces, mermelada, pan.",
      allergens: ["Lácteos", "Gluten", "Frutos secos"],
      price: "14.50 ",
    },
  ],
  ensaladas: [
    {
      image: "https://cdn.pixabay.com/photo/2021/01/10/04/37/salad-5904093_1280.jpg",
      title: "Ensalada César",
      description: "Lechuga romana, pollo a la parrilla, crutones, queso parmesano y nuestra salsa césar casera.",
      ingredients: "Lechuga, pollo, pan, queso parmesano, anchoas, limón, aceite.",
      allergens: ["Lácteos", "Gluten", "Pescado"],
      price: "11.95 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2015/05/31/13/59/salad-791891_1280.jpg",
      title: "Ensalada de Queso de Cabra",
      description: "Mezcla de lechugas con queso de cabra gratinado sobre tostadas, nueces, pasas y vinagreta de miel.",
      ingredients: "Lechugas variadas, queso de cabra, nueces, pasas, pan, miel, vinagre.",
      allergens: ["Lácteos", "Gluten", "Frutos secos"],
      price: "12.50 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2021/01/10/04/37/salad-5904093_1280.jpg",
      title: "Ensalada Mediterránea",
      description: "Tomate, pepino, cebolla roja, aceitunas, queso feta y orégano con aceite de oliva virgen extra.",
      ingredients: "Tomate, pepino, cebolla, aceitunas, queso feta, orégano, aceite de oliva.",
      allergens: ["Lácteos"],
      price: "10.95 ",
    },
  ],
  "carnes-rojas": [
    {
      image: "https://cdn.pixabay.com/photo/2018/09/14/11/12/food-3676796_1280.jpg",
      title: "Entrecot a la Parrilla",
      description: "Jugoso entrecot de vaca madurada (300g) a la parrilla con patatas asadas y verduras de temporada.",
      ingredients: "Carne de vacuno, patata, pimientos, calabacín, romero, tomillo.",
      allergens: [],
      price: "23.50 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2015/12/08/19/08/steak-1083567_1280.jpg",
      title: "Solomillo al Foie",
      description: "Medallones de solomillo de ternera con escalopa de foie, reducción de Pedro Ximénez y puré trufado.",
      ingredients: "Solomillo de ternera, foie gras, vino Pedro Ximénez, patata, trufa, mantequilla.",
      allergens: ["Lácteos"],
      price: "27.95 ",
    },
  ],
  "carnes-blancas": [
    {
      image: "https://cdn.pixabay.com/photo/2016/07/22/05/07/delicious-1534207_1280.jpg",
      title: "Pollo al Curry",
      description: "Pechuga de pollo en salsa de curry suave con leche de coco, acompañado de arroz basmati.",
      ingredients: "Pollo, curry, leche de coco, cebolla, zanahoria, pimiento, arroz.",
      allergens: [],
      price: "15.95 ",
    },
    {
      image: "https://mejorconsalud.as.com/wp-content/uploads/2021/06/pato-naranja-768x512.jpg?auto=webp&quality=7500&width=640&crop=16:9,smart,safe&format=webp&optimize=medium&dpr=2&fit=cover&fm=webp&q=75&w=640&h=360",
      title: "Confit de Pato",
      description: "Muslo de pato confitado con salsa de naranja y puré de boniato especiado.",
      ingredients: "Muslo de pato, naranja, boniato, canela, vino tinto, miel.",
      allergens: [],
      price: "19.50 ",
    },
  ],
  pescados: [
    {
      image: "https://cdn.pixabay.com/photo/2022/01/19/17/57/grilled-salmon-6950615_1280.jpg",
      title: "Salmón a la Plancha",
      description: "Lomo de salmón noruego a la plancha con salsa de eneldo y limón, acompañado de espárragos verdes.",
      ingredients: "Salmón, eneldo, limón, nata, espárragos, aceite de oliva.",
      allergens: ["Pescado", "Lácteos"],
      price: "17.95 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2021/12/14/19/58/dish-6871195_1280.jpg",
      title: "Pulpo a la Gallega",
      description: "Pulpo cocido con patatas, pimentón dulce y aceite de oliva virgen extra. Un clásico de nuestra cocina.",
      ingredients: "Pulpo, patata, pimentón, aceite de oliva, sal marina.",
      allergens: ["Moluscos"],
      price: "21.50 ",
    },
  ],
  pastas: [
    {
      image: "https://cdn.pixabay.com/photo/2018/07/18/19/12/pasta-3547078_1280.jpg",
      title: "Tagliatelle al Funghi",
      description: "Tagliatelle con salsa cremosa de setas silvestres, trufa y queso parmesano.",
      ingredients: "Pasta fresca, setas variadas, nata, trufa, queso parmesano.",
      allergens: ["Gluten", "Lácteos", "Huevo"],
      price: "14.95 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2016/03/13/09/15/food-1253393_1280.jpg",
      title: "Spaghetti alle Vongole",
      description: "Spaghetti con almejas frescas, ajo, guindilla, perejil y un toque de vino blanco.",
      ingredients: "Spaghetti, almejas, ajo, guindilla, perejil, vino blanco, aceite de oliva.",
      allergens: ["Gluten", "Moluscos"],
      price: "16.50 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2021/02/04/12/48/food-5981246_1280.jpg",
      title: "Risotto de Setas",
      description: "Arroz carnaroli cremoso con variedad de setas, mantequilla y queso parmesano.",
      ingredients: "Arroz carnaroli, caldo de verduras, setas, mantequilla, vino blanco, queso parmesano.",
      allergens: ["Lácteos"],
      price: "15.95 ",
    },
  ],
  postres: [
    {
      image: "https://cdn0.recetasgratis.net/es/posts/1/4/9/cheesecake_de_frutos_rojos_73941_600.webp",
      title: "Tarta de Queso",
      description: "Cremosa tarta de queso horneada con base de galleta y coulis de frutos rojos.",
      ingredients: "Queso crema, huevos, nata, azúcar, galletas, mantequilla, frutos rojos.",
      allergens: ["Lácteos", "Huevo", "Gluten"],
      price: "6.95 ",
    },
    {
      image: "https://foodit.lanacion.com.ar/resizer/v2/volcan-de-chocolate-con-CXHOG765K5GLJDTPXZ2FANTOHY.jpg?auth=9270572bbe0cfd089cda435b7255970994f2515fb6195c0399e2afb5faae12ad&width=880&height=586&quality=70&smart=true",
      title: "Coulant de Chocolate",
      description: "Bizcocho de chocolate con corazón líquido, acompañado de helado de vainilla.",
      ingredients: "Chocolate negro, huevos, mantequilla, harina, azúcar, helado de vainilla.",
      allergens: ["Lácteos", "Huevo", "Gluten"],
      price: "7.50 ",
    },
    {
      image: "https://cdn.pixabay.com/photo/2024/01/12/04/09/tiramisu-8503073_1280.jpg",
      title: "Tiramisú",
      description: "Clásico postre italiano con bizcochos empapados en café, mascarpone y cacao en polvo.",
      ingredients: "Queso mascarpone, bizcochos, café, huevos, azúcar, cacao en polvo.",
      allergens: ["Lácteos", "Huevo", "Gluten"],
      price: "6.50 ",
    },
  ],
  bebidas: {
    "bebidas-alcoholicas": [
      {
        image: "https://cdn.pixabay.com/photo/2018/01/12/09/45/glass-3077869_1280.jpg",
        title: "Vino Tinto Reserva",
        description: "Rioja Reserva con 24 meses de crianza en barrica de roble francés y americano.",
        ingredients: "Uva Tempranillo, Graciano y Mazuelo.",
        allergens: ["Sulfitos"],
        price: "22.00 ",
      },
      {
        image: "https://cdn.pixabay.com/photo/2017/09/23/17/35/sangria-2779570_1280.jpg",
        title: "Sangría Casera",
        description: "Refrescante sangría preparada con vino tinto, frutas troceadas y un toque de canela.",
        ingredients: "Vino tinto, naranja, limón, manzana, azúcar, canela, brandy.",
        allergens: ["Sulfitos"],
        price: "18.00  (jarra 1L)",
      },
      {
        image: "https://cdn.pixabay.com/photo/2022/12/06/05/38/cocktail-7638321_1280.jpg",
        title: "Cóctel Especial",
        description: "Cóctel exclusivo de la casa con ginebra premium, tónica, cardamomo y cítricos.",
        ingredients: "Ginebra, tónica, lima, cardamomo, pepino.",
        allergens: ["Ninguno"],
        price: "9.50 ",
      },
    ],
    "bebidas-sin-alcohol": [
      {
        image: "https://cdn.pixabay.com/photo/2015/08/25/16/12/lime-907124_1280.jpg",
        title: "Limonada Casera",
        description: "Refrescante limonada preparada al momento con limones exprimidos, menta fresca y un toque de miel.",
        ingredients: "Limón, agua, menta, miel, hielo.",
        allergens: ["Ninguno"],
        price: "4.50 ",
      },
      {
        image: "https://recetas.atma.com.ar/uploads/recetas/imagen_329.jpg",
        title: "Smoothie de Frutas",
        description: "Batido natural de frutas de temporada con yogur griego y un toque de miel.",
        ingredients: "Fresas, plátano, kiwi, yogur griego, miel.",
        allergens: ["Lácteos"],
        price: "5.95 ",
      },
      {
        image: "https://cdn.pixabay.com/photo/2014/12/11/02/57/coffee-563800_1280.jpg",
        title: "Café Especial",
        description: "Café arábica de origen único preparado con método alternativo a elegir (chemex, aeropress o v60).",
        ingredients: "Café de especialidad 100% arábica.",
        allergens: ["Ninguno"],
        price: "3.95 ",
      },
    ],
  },
};

export default menuData;